// packages/vue3-table/src/lib/GuiexpertTable.vue
<template>
  <div
    ref="root"
    class="container-div"
    style="width: 100%; height: 100%; background-color: transparent; padding: 0; margin: 0">
  </div>
</template>

<script lang="ts">
import {
  FocusModelIf,
  GeModelChangeEvent,
  GeMouseEvent,
  LicenseManager, SelectionModelIf,
  SimpleDomService,
  TableOptions,
  TableScope
} from '@guiexpert/table';
import { defineComponent, onMounted, ref } from "vue";


export default defineComponent({
  inheritAttrs: false,
  props: {
    tableModel: {
      required: true
    },
    tableOptions: {
      required: false,
      default: new TableOptions()
    },
    debounceMouseClickDelay: {
      required: false,
      default: 150
    },
    licenseKey: {
      default: '',
      required: false
    }
  },
  emits: [
    "tableReady",
    "mouseClicked",
    "mouseDragging",
    "checkboxChanged",
    "contextmenu",
    "modelChanged",
    "focusChanged",
    "selectionChanged",
    "mouseDraggingEnd",
    "mouseMoved"
  ],

  setup(props, { emit }) {
    const root = ref(null);

    const initTable = (ele: HTMLDivElement) => {

      const listener = {

        onSelectionChanged: (evt: SelectionModelIf) => {
          emit("selectionChanged", evt);
        },

        onFocusChanged: (evt: FocusModelIf) => {
          emit("focusChanged", evt);
        },

        onCheckboxChanged: (evt: any[]) => {
          emit("checkboxChanged", evt);
        },

        onContextmenu: (evt: GeMouseEvent) => {
          emit("contextmenu", evt);
        },

        onModelChanged: (evt: GeModelChangeEvent) => {
          emit("modelChanged", evt);
        },

        onMouseClicked: (evt: GeMouseEvent) => {
          emit("mouseClicked", evt);
        },

        onMouseDragging: (evt: GeMouseEvent) => {
          emit("mouseDragging", evt);
        },

        onMouseDraggingEnd: (evt: GeMouseEvent) => {
          emit("mouseDraggingEnd", evt);
        },

        onMouseMoved: (evt: GeMouseEvent) => {
          emit("mouseMoved", evt);
        }
      };

      const tableScope = new TableScope(
        ele, props.tableModel, new SimpleDomService(), props.tableOptions, listener
      );
      tableScope.firstInit();
      emit("tableReady", tableScope.getApi());
    };


    onMounted(() => {
      if (root.value) {
        initTable(root.value as HTMLDivElement);
      }
    });

    if (props.licenseKey) LicenseManager.getInstance().setLicenseKey(props.licenseKey);

    return {
      root
    };
  }
});

</script>

<style >
@import "../../../table/css/main.css";
</style>

// packages/webcomponent-table/src/lib/guiexpert-table.ts
import {
  EventListenerIf, FocusModelIf,
  GeModelChangeEvent,
  GeMouseEvent, LicenseManager, SelectionModelIf,
  SimpleDomService,
  TableModelAndOptionsIf,
  TableScope
} from '@guiexpert/table';

export class GuiexpertTable extends HTMLElement {


  private _data: TableModelAndOptionsIf | undefined;


  get data(): TableModelAndOptionsIf | undefined {
    return this._data;
  }

  set data(value: TableModelAndOptionsIf | undefined) {
    this._data = value;
    if (value) {
      this.setData(value);
    }
  }

  set licenseKey(key: string){
    LicenseManager.getInstance().setLicenseKey(key);
  }

  public setData({ tableModel, tableOptions }: TableModelAndOptionsIf) {

    this.innerHTML = `
     <div
      class="container-div"
      style="width: 100%; height: 100%; background-color: transparent; padding: 0; margin: 0; display: block"></div>
    `;

    const ele = this.querySelector("div") as HTMLDivElement;

    const domService = new SimpleDomService();
    if (tableModel) {

      const listener: EventListenerIf = {
        onSelectionChanged(model: SelectionModelIf): void {
          const e = new CustomEvent("selectionChanged", { detail: model, bubbles: true });
          ele.dispatchEvent(e);
        },

        onFocusChanged(model: FocusModelIf): void{
          const e = new CustomEvent("focusChanged", { detail: model, bubbles: true });
          ele.dispatchEvent(e);
        },

        onCheckboxChanged: (evt: any[]) => {
          const e = new CustomEvent("checkboxChanged", { detail: evt, bubbles: true });
          ele.dispatchEvent(e);
        },

        onContextmenu: (evt: GeMouseEvent) => {
          const e = new CustomEvent("contextmenu", { detail: evt, bubbles: true });
          ele.dispatchEvent(e);
        },

        onModelChanged: (evt: GeModelChangeEvent) => {
          const e = new CustomEvent("modelChanged", { detail: evt, bubbles: true });
          ele.dispatchEvent(e);
        },

        onMouseClicked: (evt: GeMouseEvent) => {
          const e = new CustomEvent("mouseClicked", { detail: evt, bubbles: true });
          ele.dispatchEvent(e);
        },

        onMouseDragging: (evt: GeMouseEvent) => {
          const e = new CustomEvent("mouseDragging", { detail: evt, bubbles: true });
          ele.dispatchEvent(e);
        },

        onMouseDraggingEnd: (evt: GeMouseEvent) => {
          const e = new CustomEvent("mouseDraggingEnd", { detail: evt, bubbles: true });
          ele.dispatchEvent(e);
        },

        onMouseMoved: (evt: GeMouseEvent) => {
          const e = new CustomEvent("mouseMoved", { detail: evt, bubbles: true });
          ele.dispatchEvent(e);
        }
      };

      const tableScope = new TableScope(
        ele, tableModel, domService, tableOptions, listener
      );
      domService.setStyle(ele, "height", "100%");
      domService.setStyle(ele, "width", "100%");
      tableScope.firstInit();

      const e = new CustomEvent("tableReady", { detail: tableScope.getApi(), bubbles: true });
      ele.dispatchEvent(e);
    }
  }

  connectedCallback() {
    //
  }
}


// we do this in the demo app: customElements.define("guiexpert-table", GuiexpertTable);
