// libs/vue3-table/src/lib/GuiexpertTable.vue
<template>
  <div
    ref="root"
    class="container-div"
    style="width: 100%; height: 100%; background-color: transparent; padding: 0; margin: 0">
  </div>
</template>

<script lang="ts">
import { GeModelChangeEvent, GeMouseEvent, SimpleDomService, TableOptions, TableScope } from "@guiexpert/table";
import { defineComponent, onMounted, ref } from "vue";


export default defineComponent({
  inheritAttrs: false,
  props: {
    tableModel: {
      required: true
    },
    tableOptions: {
      required: false,
      default: new TableOptions()
    },
    debounceMouseClickDelay: {
      required: false,
      default: 150
    }
  },
  emits: [
    "tableReady",
    "mouseClicked",
    "mouseDragging",
    "checkboxChanged",
    "contextmenu",
    "modelChanged",
    "mouseDraggingEnd",
    "mouseMoved"
  ],

  setup(props, { emit }) {
    const root = ref(null);

    const initTable = (ele: HTMLDivElement) => {

      const listener = {

        onCheckboxChanged: (evt: any[]) => {
          emit("checkboxChanged", evt);
        },

        onContextmenu: (evt: GeMouseEvent) => {
          emit("contextmenu", evt);
        },

        onModelChanged: (evt: GeModelChangeEvent) => {
          emit("modelChanged", evt);
        },

        onMouseClicked: (evt: GeMouseEvent) => {
          emit("mouseClicked", evt);
        },

        onMouseDragging: (evt: GeMouseEvent) => {
          emit("mouseDragging", evt);
        },

        onMouseDraggingEnd: (evt: GeMouseEvent) => {
          emit("mouseDraggingEnd", evt);
        },

        onMouseMoved: (evt: GeMouseEvent) => {
          emit("mouseMoved", evt);
        }
      };

      const tableScope = new TableScope(
        ele, props.tableModel, new SimpleDomService(), props.tableOptions, listener
      );
      tableScope.firstInit();
      emit("tableReady", tableScope.getApi());
    };


    onMounted(() => {
      if (root.value) {
        initTable(root.value as HTMLDivElement);
      }
    });

    return {
      root
    };
  }
});

</script>

// libs/preact-table/src/GuiexpertTable.tsx
import { Component, createRef } from "preact";
import {
  GeModelChangeEvent,
  GeMouseEvent,
  SimpleDomService,
  TableModelIf,
  TableOptions,
  TableScope
} from "@guiexpert/table";
import { GeCheckboxEventFn, GeModelChangeEventFn, GeMouseEventFn, GeTableReadyEventFn } from "@guiexpert/react-table";

export interface GuiexpertTableProps {
  tableModel: TableModelIf,
  tableOptions?: TableOptions,
  mouseMoved?: GeMouseEventFn,
  contextmenu?: GeMouseEventFn,
  mouseClicked?: GeMouseEventFn,
  mouseDragging?: GeMouseEventFn,
  mouseDraggingEnd?: GeMouseEventFn,
  checkboxChanged?: GeCheckboxEventFn,
  modelChanged?: GeModelChangeEventFn,
  tableReady?: GeTableReadyEventFn
}


export class GuiexpertTable extends Component {

  ref = createRef();

  constructor(props: GuiexpertTableProps) {
    super(props);
  }

  componentDidMount() {
    const myContainer: HTMLDivElement = this.ref.current;
    this.initTable(myContainer, this.props as GuiexpertTableProps);
  }

  componentWillUnmount() {
  }

  initTable(ele: HTMLDivElement, props: GuiexpertTableProps) {
    const listener = {
      onCheckboxChanged: (evt: any[]) => {
        if (props.checkboxChanged) {
          props.checkboxChanged(evt);
        }
      },

      onContextmenu: (evt: GeMouseEvent) => {
        if (props.contextmenu) {
          props.contextmenu(evt);
        }
      },

      onModelChanged: (evt: GeModelChangeEvent) => {
        if (props.modelChanged) {
          props.modelChanged(evt);
        }
      },

      onMouseClicked: (evt: GeMouseEvent) => {
        if (props.mouseClicked) {
          props.mouseClicked(evt);
        }
      },

      onMouseDragging: (evt: GeMouseEvent) => {
        if (props.mouseDragging) {
          props.mouseDragging(evt);
        }
      },

      onMouseDraggingEnd: (evt: GeMouseEvent) => {
        if (props.mouseDraggingEnd) {
          props.mouseDraggingEnd(evt);
        }
      },

      onMouseMoved: (evt: GeMouseEvent) => {
        // if (mouseMoved) {
        //   mouseMoved(evt);
        // }
      }
    };

    const tableScope = new TableScope(
      ele, props.tableModel, new SimpleDomService(), props.tableOptions ?? new TableOptions(), listener
    );
    tableScope.firstInit();
    if (props.tableReady) {
      props.tableReady(tableScope.getApi());
    }
  };

  render() {
    return <div
      ref={this.ref}
      className="container-div"
      style={{
        width: "100%",
        height: "100%",
        backgroundColor: "transparent",
        padding: "0",
        margin: "0"
      }} />;
  }
}

export default GuiexpertTable;
