// apps/svelte-table-demo/src/App.svelte
<script lang="ts">

  import { ComponentRendererWrapper, GuiexpertTable } from "@guiexpert/svelte-table";
  import { ColumnDefIf, TableFactory, TreeFactory } from "@guiexpert/table";
  import {
    applyBodyRenderer,
    createColumnDefs,
    createTableOptions,
    createTableRows, SimplePersonIf
  } from "@guiexpert/demo-table-models";
  import { default as GenderRendererComponent } from "./GenderRendererComponent.svelte";

  const tableOptions = createTableOptions();
  const rows: SimplePersonIf[] = createTableRows();
  const columnDefs: ColumnDefIf[] = createColumnDefs();
  applyBodyRenderer(columnDefs[2], new ComponentRendererWrapper(GenderRendererComponent));
  const tableModel = TableFactory.buildByTypedRowsParam({
    rows,
    columnDefs,
    tableOptions,
    fixedLeftColumnCount: 0
  });

  function handleTableReady(api) {
    console.info("Table API:", api.detail);
  }

  function handleMouseClicked(evt) {
    console.info("Mouse clicked:", evt.detail);
  }
</script>

<main>
  <GuiexpertTable
    on:mouseClicked={handleMouseClicked}
    on:tableReady={handleTableReady}
    tableModel={tableModel}
    tableOptions={tableOptions}
  ></GuiexpertTable>
</main>

<style>
</style>

// apps/preact-table-demo/src/App.tsx
import { ComponentRendererWrapper, GuiexpertTable } from "@guiexpert/preact-table";
import {
  applyBodyRenderer,
  createColumnDefs,
  createTableOptions,
  createTableRows,
  SimplePersonIf
} from "@guiexpert/demo-table-models";
import { ColumnDefIf, TableApi, TreeFactory } from "@guiexpert/table";
import GenderRendererComponent from "./GenderRendererComponent";

function App() {

  const tableOptions = createTableOptions();
  const rows: SimplePersonIf[] = createTableRows();
  const columnDefs: ColumnDefIf[] = createColumnDefs();
  applyBodyRenderer(columnDefs[2], new ComponentRendererWrapper(GenderRendererComponent));
  const tableModel = TableFactory.buildByTypedRowsParam({
    rows,
    columnDefs,
    tableOptions,
    fixedLeftColumnCount: 1
  });

  function tableReady(api: TableApi) {
    console.info("Table API:", api);
  }

  return (
    <GuiexpertTable
      tableOptions={tableOptions}
      tableModel={tableModel}
      mouseClicked={console.info}
      tableReady={tableReady}
    />
  );
}

export default App;
