// libs/vue3-table/src/lib/GuiexpertTable.vue
<template>
  <div
    ref="root"
    class="container-div"
    style="width: 100%; height: 100%; background-color: transparent; padding: 0; margin: 0">
  </div>
</template>

<script lang="ts">
import { GeModelChangeEvent, GeMouseEvent, SimpleDomService, TableOptions, TableScope } from "@guiexpert/table";
import { defineComponent, onMounted, ref } from "vue";


export default defineComponent({
  inheritAttrs: false,
  props: {
    tableModel: {
      required: true
    },
    tableOptions: {
      required: false,
      default: new TableOptions()
    },
    debounceMouseClickDelay: {
      required: false,
      default: 150
    }
  },
  emits: [
    "tableReady",
    "mouseClicked",
    "mouseDragging",
    "checkboxChanged",
    "contextmenu",
    "modelChanged",
    "mouseDraggingEnd",
    "mouseMoved"
  ],

  setup(props, { emit }) {
    const root = ref(null);

    const initTable = (ele: HTMLDivElement) => {

      const listener = {

        onCheckboxChanged: (evt: any[]) => {
          emit("checkboxChanged", evt);
        },

        onContextmenu: (evt: GeMouseEvent) => {
          emit("contextmenu", evt);
        },

        onModelChanged: (evt: GeModelChangeEvent) => {
          emit("modelChanged", evt);
        },

        onMouseClicked: (evt: GeMouseEvent) => {
          emit("mouseClicked", evt);
        },

        onMouseDragging: (evt: GeMouseEvent) => {
          emit("mouseDragging", evt);
        },

        onMouseDraggingEnd: (evt: GeMouseEvent) => {
          emit("mouseDraggingEnd", evt);
        },

        onMouseMoved: (evt: GeMouseEvent) => {
          emit("mouseMoved", evt);
        }
      };

      const tableScope = new TableScope(
        ele, props.tableModel, new SimpleDomService(), props.tableOptions, listener
      );
      tableScope.firstInit();
      emit("tableReady", tableScope.getApi());
    };


    onMounted(() => {
      if (root.value) {
        initTable(root.value as HTMLDivElement);
      }
    });

    return {
      root
    };
  }
});

</script>

// libs/react-table/src/lib/guiexpert-table.tsx
import {
  GeModelChangeEvent,
  GeMouseEvent,
  SimpleDomService,
  TableApi,
  TableModelIf,
  TableOptions,
  TableScope
} from "@guiexpert/table";
import React, { useEffect, useRef } from "react";

export type GeMouseEventFn = (evt: GeMouseEvent) => {};
export type GeCheckboxEventFn = (evt: any[]) => {};
export type GeTableReadyEventFn = (evt: TableApi) => {};
export type GeModelChangeEventFn = (evt: GeModelChangeEvent) => {};

export interface GuiexpertTableProps {
  tableModel: TableModelIf,
  tableOptions?: TableOptions,
  mouseMoved?: GeMouseEventFn,
  contextmenu?: GeMouseEventFn,
  mouseClicked?: GeMouseEventFn,
  mouseDragging?: GeMouseEventFn,
  mouseDraggingEnd?: GeMouseEventFn,
  checkboxChanged?: GeCheckboxEventFn,
  modelChanged?: GeModelChangeEventFn,
  tableReady?: GeTableReadyEventFn
}

export function GuiexpertTable(
  {
    tableModel,
    tableOptions = new TableOptions(),
    mouseMoved,
    checkboxChanged,
    contextmenu,
    modelChanged,
    mouseClicked,
    mouseDragging,
    mouseDraggingEnd,
    tableReady
  }: GuiexpertTableProps) {

  const myContainer = useRef(null);
  let initialized = false;

  useEffect(() => {
    if (myContainer.current && !initialized) {
      initTable(myContainer.current);
      initialized = true;
    }
  });

  let root: HTMLDivElement | null;

  const initTable = (ele: HTMLDivElement) => {
    const listener = {
      onCheckboxChanged: (evt: any[]) => {
        if (checkboxChanged) {
          checkboxChanged(evt);
        }
      },

      onContextmenu: (evt: GeMouseEvent) => {
        if (contextmenu) {
          contextmenu(evt);
        }
      },

      onModelChanged: (evt: GeModelChangeEvent) => {
        if (modelChanged) {
          modelChanged(evt);
        }
      },

      onMouseClicked: (evt: GeMouseEvent) => {
        if (mouseClicked) {
          mouseClicked(evt);
        }
      },

      onMouseDragging: (evt: GeMouseEvent) => {
        if (mouseDragging) {
          mouseDragging(evt);
        }
      },

      onMouseDraggingEnd: (evt: GeMouseEvent) => {
        if (mouseDraggingEnd) {
          mouseDraggingEnd(evt);
        }
      },

      onMouseMoved: (evt: GeMouseEvent) => {
        if (mouseMoved) {
          mouseMoved(evt);
        }
      }
    };

    const tableScope = new TableScope(
      ele, tableModel, new SimpleDomService(), tableOptions, listener
    );
    tableScope.firstInit();
    if (tableReady) {
      tableReady(tableScope.getApi());
    }
  };

  return (
    <div
      ref={myContainer}
      className="container-div"
      style={{
        width: "100%",
        height: "100%",
        background: "transparent",
        padding: "0",
        margin: "0"
      }}></div>
  );
}

export default GuiexpertTable;
