// apps/react-table-demo/src/app/app.tsx
import { ComponentRendererWrapper, GeMouseEventFn, GuiexpertTable } from "@guiexpert/react-table";
import { ColumnDefIf, TreeFactory, TableOptions, TableFactory } from "@guiexpert/table";
import {
  applyBodyRenderer,
  createColumnDefs,
  createTableOptions,
  createTableRows,
  SimplePersonIf
} from "@guiexpert/demo-table-models";
import GenderRendererComponent from "./GenderRendererComponent";

export function App() {


  const tableOptions = createTableOptions();
  const rows: SimplePersonIf[] = createTableRows();
  const columnDefs: ColumnDefIf[] = createColumnDefs();
  applyBodyRenderer(columnDefs[2], new ComponentRendererWrapper(GenderRendererComponent));
  const tableModel = TableFactory.buildByTypedRowsParam({
    rows,
    columnDefs,
    tableOptions,
    fixedLeftColumnCount: 0
  });

  return (
    <>
      <GuiexpertTable
        tableModel={tableModel}
        tableOptions={new TableOptions}
        mouseClicked={console.info as GeMouseEventFn}
      />
    </>
  );
}

export default App;

// apps/svelte-table-demo/src/App.svelte
<script lang="ts">

  import { ComponentRendererWrapper, GuiexpertTable } from "@guiexpert/svelte-table";
  import { ColumnDefIf, TableFactory, TreeFactory } from "@guiexpert/table";
  import {
    applyBodyRenderer,
    createColumnDefs,
    createTableOptions,
    createTableRows, SimplePersonIf
  } from "@guiexpert/demo-table-models";
  import { default as GenderRendererComponent } from "./GenderRendererComponent.svelte";

  const tableOptions = createTableOptions();
  const rows: SimplePersonIf[] = createTableRows();
  const columnDefs: ColumnDefIf[] = createColumnDefs();
  applyBodyRenderer(columnDefs[2], new ComponentRendererWrapper(GenderRendererComponent));
  const tableModel = TableFactory.buildByTypedRowsParam({
    rows,
    columnDefs,
    tableOptions,
    fixedLeftColumnCount: 0
  });

  function handleTableReady(api) {
    console.info("Table API:", api.detail);
  }

  function handleMouseClicked(evt) {
    console.info("Mouse clicked:", evt.detail);
  }
</script>

<main>
  <GuiexpertTable
    on:mouseClicked={handleMouseClicked}
    on:tableReady={handleTableReady}
    tableModel={tableModel}
    tableOptions={tableOptions}
  ></GuiexpertTable>
</main>

<style>
</style>
