// libs/svelte-table/src/GuiexpertTable.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import { EventListenerIf, FocusModelIf, LicenseManager, SelectionModelIf, SimpleDomService, TableOptions, TableScope } from '../../table/src'; // "@guiexpert/table";

  export let tableModel: any;
  export let tableOptions = new TableOptions();
  export let licenseKey: string | undefined;

  let root: any;
  const dispatch = createEventDispatcher();

  onMount(() => {

    const listener: EventListenerIf = {
      onSelectionChanged(model: SelectionModelIf): void {
        dispatch('selectionChanged', model);
      },
      onFocusChanged(model: FocusModelIf): void{
        dispatch('focusChanged', model);
      },
      onCheckboxChanged: (evt: any) => {
        dispatch('checkboxChanged', evt);
      },

      onContextmenu: (evt: any) => {
        dispatch('contextmenu', evt);
      },

      onModelChanged: (evt: any) => {
        dispatch('modelChanged', evt);
      },

      onMouseClicked: (evt: any) => {
        dispatch('mouseClicked', evt);
      },

      onMouseDragging: (evt: any) => {
        dispatch('mouseDragging', evt);
      },

      onMouseDraggingEnd: (evt: any) => {
        dispatch('mouseDraggingEnd', evt);
      },

      onMouseMoved: (evt: any) => {
        dispatch('mouseMoved', evt);
      }
    };

    const tableScope = new TableScope(
      root, tableModel, new SimpleDomService(), tableOptions, listener
    );
    tableScope.firstInit();
    dispatch('tableReady', tableScope.getApi());

    if (licenseKey) LicenseManager.getInstance().setLicenseKey(licenseKey);
  });
</script>

<div
  bind:this={root}
  class="ge-table"
  style="width: 100%; height: 100%; background-color: transparent; padding: 0; margin: 0"></div>

<style>

</style>

// packages/vue3-table/src/lib/GuiexpertTable.vue
<template>
  <div
    ref="root"
    class="container-div"
    style="width: 100%; height: 100%; background-color: transparent; padding: 0; margin: 0">
  </div>
</template>

<script lang="ts">
import {
  FocusModelIf,
  GeModelChangeEvent,
  GeMouseEvent,
  LicenseManager, SelectionModelIf,
  SimpleDomService,
  TableOptions,
  TableScope
} from '@guiexpert/table';
import { defineComponent, onMounted, ref } from "vue";


export default defineComponent({
  inheritAttrs: false,
  props: {
    tableModel: {
      required: true
    },
    tableOptions: {
      required: false,
      default: new TableOptions()
    },
    debounceMouseClickDelay: {
      required: false,
      default: 150
    },
    licenseKey: {
      default: '',
      required: false
    }
  },
  emits: [
    "tableReady",
    "mouseClicked",
    "mouseDragging",
    "checkboxChanged",
    "contextmenu",
    "modelChanged",
    "focusChanged",
    "selectionChanged",
    "mouseDraggingEnd",
    "mouseMoved"
  ],

  setup(props, { emit }) {
    const root = ref(null);

    const initTable = (ele: HTMLDivElement) => {

      const listener = {

        onSelectionChanged: (evt: SelectionModelIf) => {
          emit("selectionChanged", evt);
        },

        onFocusChanged: (evt: FocusModelIf) => {
          emit("focusChanged", evt);
        },

        onCheckboxChanged: (evt: any[]) => {
          emit("checkboxChanged", evt);
        },

        onContextmenu: (evt: GeMouseEvent) => {
          emit("contextmenu", evt);
        },

        onModelChanged: (evt: GeModelChangeEvent) => {
          emit("modelChanged", evt);
        },

        onMouseClicked: (evt: GeMouseEvent) => {
          emit("mouseClicked", evt);
        },

        onMouseDragging: (evt: GeMouseEvent) => {
          emit("mouseDragging", evt);
        },

        onMouseDraggingEnd: (evt: GeMouseEvent) => {
          emit("mouseDraggingEnd", evt);
        },

        onMouseMoved: (evt: GeMouseEvent) => {
          emit("mouseMoved", evt);
        }
      };

      const tableScope = new TableScope(
        ele, props.tableModel, new SimpleDomService(), props.tableOptions, listener
      );
      tableScope.firstInit();
      emit("tableReady", tableScope.getApi());
    };


    onMounted(() => {
      if (root.value) {
        initTable(root.value as HTMLDivElement);
      }
    });

    if (props.licenseKey) LicenseManager.getInstance().setLicenseKey(props.licenseKey);

    return {
      root
    };
  }
});

</script>

<style >
@import "../../../table/css/main.css";
</style>
