// packages/react-table/src/lib/component-renderer-wrapper.ts
import { AreaIdent, AreaModelIf, CellRendererIf, DomServiceIf, RendererCleanupFnType } from "@guiexpert/table";
import { createRoot } from "react-dom/client";


export class ComponentRendererWrapper implements CellRendererIf {

  constructor(
    private readonly Component: any
  ) {
    console.info(Component);
  }

  render(
    cellDiv: HTMLDivElement,
    rowIndex: number,
    columnIndex: number,
    areaIdent: AreaIdent,
    areaModel: AreaModelIf,
    cellValue: any,
    domService: DomServiceIf): RendererCleanupFnType | undefined {

    const props = {
      cellDiv,
      rowIndex,
      columnIndex,
      areaIdent,
      areaModel,
      cellValue
    };
    const root = createRoot(cellDiv, {});
    root.render(this.Component(props));

    return () => {
      root.unmount();
    };
  }


}

// packages/solid-table/src/ComponentRendererWrapper.ts
import { AreaIdent, AreaModelIf, CellRendererIf, DomServiceIf, RendererCleanupFnType } from "@guiexpert/table";
import { JSX } from "solid-js/jsx-runtime";
import { mergeProps, render } from "solid-js/web";

export class ComponentRendererWrapper implements CellRendererIf {

  constructor(
    private readonly code: (props: any) => JSX.Element
  ) {
  }

  render(
    cellDiv: HTMLDivElement,
    rowIndex: number,
    columnIndex: number,
    areaIdent: AreaIdent,
    areaModel: AreaModelIf,
    cellValue: any,
    _domService: DomServiceIf): RendererCleanupFnType | undefined {

    const props = mergeProps({
      rowIndex,
      columnIndex,
      areaIdent,
      areaModel,
      cellValue
    });
    render(
      () => this.code(props),
      cellDiv
    );

    return undefined;
  }


}
