// packages/svelte-table/src/GuiexpertTable.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte';
  import { EventListenerIf, FocusModelIf, LicenseManager, SelectionModelIf, SimpleDomService, TableOptions, TableScope } from '../../table/src'; // "@guiexpert/table";

  export let tableModel: any;
  export let tableOptions = new TableOptions();
  export let licenseKey: string | undefined;

  let root: any;
  const dispatch = createEventDispatcher();

  onMount(() => {

    const listener: EventListenerIf = {
      onSelectionChanged(model: SelectionModelIf): void {
        dispatch('selectionChanged', model);
      },
      onFocusChanged(model: FocusModelIf): void{
        dispatch('focusChanged', model);
      },
      onCheckboxChanged: (evt: any) => {
        dispatch('checkboxChanged', evt);
      },

      onContextmenu: (evt: any) => {
        dispatch('contextmenu', evt);
      },

      onModelChanged: (evt: any) => {
        dispatch('modelChanged', evt);
      },

      onMouseClicked: (evt: any) => {
        dispatch('mouseClicked', evt);
      },

      onMouseDragging: (evt: any) => {
        dispatch('mouseDragging', evt);
      },

      onMouseDraggingEnd: (evt: any) => {
        dispatch('mouseDraggingEnd', evt);
      },

      onMouseMoved: (evt: any) => {
        dispatch('mouseMoved', evt);
      },

      onScroll: (evt: any) => {
        dispatch('scroll', evt);
      }
    };

    const tableScope = new TableScope(
      root, tableModel, new SimpleDomService(), tableOptions, listener
    );
    tableScope.firstInit();
    dispatch('tableReady', tableScope.getApi());

    if (licenseKey) LicenseManager.getInstance().setLicenseKey(licenseKey);
  });
</script>

<div
  bind:this={root}
  class="ge-table"
  style="width: 100%; height: 100%; background-color: transparent; padding: 0; margin: 0"></div>

<style>

</style>

// packages/solid-table/src/GuiexpertTable.tsx
import {GuiexpertTableProps} from "./GuiexpertTableProps";
import {mergeProps, onMount} from "solid-js";
import {
  EventListenerIf,
  FocusModelIf, GeScrollEvent,
  LicenseManager,
  SelectionModelIf,
  SimpleDomService,
  TableOptions,
  TableScope
} from '@guiexpert/table';



/**
 * Render a table component with specified properties
 *
 * @param {GuiexpertTableProps} props - The properties of the table component
 * @returns {JSX.Element} - The rendered table component
 */
export default (props: GuiexpertTableProps) => {

  let ref:any;

  const merged = mergeProps({
    tableModel: null,
    tableOptions: new TableOptions()
  }, props);


  onMount(() => {
    const listener: EventListenerIf = {
      onSelectionChanged(model: SelectionModelIf): void {
        const e = new CustomEvent("selectionChanged", { detail: model, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onScroll(model: GeScrollEvent): void {
        const e = new CustomEvent("scroll", { detail: model, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onFocusChanged(model: FocusModelIf): void{
        const e = new CustomEvent("focusChanged", { detail: model, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onCheckboxChanged: (evt: any) => {
        const e = new CustomEvent("checkboxChanged", { detail: evt, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onContextmenu: (evt: any) => {
        const e = new CustomEvent("contextmenu", { detail: evt, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onModelChanged: (evt: any) => {
        const e = new CustomEvent("modelChanged", { detail: evt, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onMouseClicked: (evt: any) => {
        const e = new CustomEvent("mouseClicked", { detail: evt, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onMouseDragging: (evt: any) => {
        const e = new CustomEvent("mouseDragging", { detail: evt, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onMouseDraggingEnd: (evt: any) => {
        const e = new CustomEvent("mouseDraggingEnd", { detail: evt, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      },

      onMouseMoved: (evt: any) => {
        const e = new CustomEvent("mouseMoved", { detail: evt, bubbles: true });
        if (ref) ref.dispatchEvent(e);
      }
    };

    const tableScope = new TableScope(
      ref, merged.tableModel, new SimpleDomService(), merged.tableOptions, listener
    );
    tableScope.firstInit();
    const e = new CustomEvent("tableReady", { detail: tableScope.getApi(), bubbles: true });
    if (ref) ref.dispatchEvent(e);

    if (merged.licenseKey) LicenseManager.getInstance().setLicenseKey(merged.licenseKey);
  });

  return (
    <div ref={ref} />
  );
}
