// apps/svelte-table-demo/src/App.svelte
<script lang="ts">

  import { ComponentRendererWrapper, GuiexpertTable } from "@guiexpert/svelte-table";
  import {ColumnDefIf, TableFactory} from "@guiexpert/table";
  import {
    applyBodyRenderer,
    createColumnDefs,
    createTableOptions,
    createTableRows, SimplePersonIf
  } from "@guiexpert/demo-table-models";
  import { default as GenderRendererComponent } from "./GenderRendererComponent.svelte";


  const tableOptions = createTableOptions();
  const rows: SimplePersonIf[] = createTableRows();
  const columnDefs: ColumnDefIf[] = createColumnDefs();
  // applyBodyRenderer(columnDefs[2], new ComponentRendererWrapper(GenderRendererComponent));
  const tableModel = TableFactory.buildByTypedRowsParam({
    rows,
    columnDefs,
    tableOptions,
    fixedLeftColumnCount: 0
  });
  console.info('columnDefs', columnDefs);
  console.info('rows', rows);

  function handleTableReady(api: CustomEvent) {
    console.info("Table API:", api.detail);
  }

  function handleMouseClicked(evt: CustomEvent) {
    console.info("Mouse clicked:", evt.detail);
  }
</script>


<GuiexpertTable
  on:mouseClicked={handleMouseClicked}
  on:tableReady={handleTableReady}
  tableModel={tableModel}
  tableOptions={tableOptions}
></GuiexpertTable>

// apps/solid-table-demo/src/App.tsx
import {ComponentRendererWrapper} from "@guiexpert/solid-table";
import {onMount} from "solid-js";
import {GuiexpertTable} from "@guiexpert/solid-table";
import {ColumnDefIf, GeMouseEvent, TableFactory} from "@guiexpert/table";
import {
  applyBodyRenderer, createColumnDefs, createTableOptions, createTableRows, SimplePersonIf
} from "@guiexpert/demo-table-models";
import {default as GenderRendererComponent} from "./GenderRendererComponent";


const tableOptions = createTableOptions();
const rows: SimplePersonIf[] = createTableRows();
const columnDefs: ColumnDefIf[] = createColumnDefs();
applyBodyRenderer(columnDefs[2], new ComponentRendererWrapper(GenderRendererComponent));
const tableModel = TableFactory.buildByTypedRowsParam({
  rows, columnDefs, tableOptions, fixedLeftColumnCount: 0
});


function handleTableReady(api: any) {
  console.info("Table API:", api.detail);
}


function App() {
  let ref: any;

  onMount(() => {
    ref.addEventListener("mouseClicked", (e: CustomEvent<GeMouseEvent>) => console.info(e));
    ref.addEventListener("mouseMoved", (e: CustomEvent<GeMouseEvent>) => document.title = e.detail.rowIndex + "/" + e.detail.columnIndex);
    ref.addEventListener("tableReady", handleTableReady);
  });


  return (<div ref={ref}>
    <GuiexpertTable
      tableModel={tableModel}
      tableOptions={tableOptions}/>
  </div>);
}


export default App;
